### ISSUE TITLE
unable to use - make-make.html hangs

### ISSUE THREAD

**Issue by zawsx** [probins/map-make#10]
Arrived here because I'd like to provide various OrdSurv features to an OL3/OSM-based map.
In a post you made on an Ordnance Survey forum, you mentioned the need to re-project either the OrdSurv layer or all the others. Had hoped not to have to reproject but it looks as if I'll have to.

You pointed to:
https://maps.peterrobins.co.uk/gb.html
which hangs as you have deprecated it. I could not find it in your repos here.

I can't tell if the projections are in fact accurate enough to be overlaid at zoom level 17 - was hoping to find out with map make. Not clear to me what make-make does exactly and there are no screenshots. 

As per the instructions, I downloaded just the one file (make-make.html) and ran it on my 'fake' tld on my local machine. I noticed a post you made a while back 
An alert appears with 'Error reading map-make.js', errors are logged to the console and it hangs the the 'loading' gif.

I see there are two places the alerted error is generated from (you might want to change their wording to differentiate them). The one I get comes from initloader.js
The console errors are:
```
mapDef.src.js:71    Uncaught TypeError: Cannot read property 'lat' of undefined

map-make.src.js:86  Uncaught TypeError: mapDef.init is not a function(anonymous function) @ map-make.src.js:86(anonymous function) @ map-make.src.js:148J @ system.src.js:6d.execute @ system.src.js:7s @ system.src.js:7n @ system.src.js:7execute @ system.src.js:7y @ system.src.js:6w @ system.src.js:6p @ system.src.js:6h @ system.src.js:6(anonymous function) @ system.src.js:6
szmap-make.htm:15 Uncaught TypeError: mapDef.init is not a function
	Evaluating https://github.jspm.io/probins/map-make@master/map-make.js
	Error loading https://github.jspm.io/probins/map-make@master/map-make.js

Invoking 'alert()' during microtask execution is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5647113010544640 for more details.

undefined:1 Uncaught (in promise) Uncaught TypeError: Cannot read property 'lat' of undefined
	Evaluating https://github.jspm.io/probins/map-make@master/mapDef.js
	Error loading https://github.jspm.io/probins/map-make@master/mapDef.js
```
-------------------------------
Hope that helps

**Comment by probins** [comment]
oops, forgot to test a previous change without any parameters. Should be fixed with https://github.com/probins/map-make/commit/d389be9f506a9293fad8bf813745c8c09be6cd7e. Try again.

Not sure what you mean by 'fake' tld, but if you want to use with OpenSpace servers, your referrer will have to match the one registered for the api key you enter with map-make. I hope to improve the docs shortly.

**Comment by zawsx** [comment]
Wow, thanks for the quick response - appreciated.  Works fine now.  I already have an OrdSurv API key.
What I mean by 'fake' tld is that I add 
192.168.10.67 example.tld 
to my hosts file on my local machine to better reflect reality. 

You might want to supply the example with default values in a popup, maye an OL3 Context menu.
There isn't much help on the page. Wasn't obvious that clicking in the input fields yielded some.
I was stumped at each input field (because I'm an idiot, no doubt).  
I didn't realise, for instance:
a) what the 'CODE' field was for and having figured it out, chose gb (not sure why it appended /os - what are the other map provider codes?) 
b) that the API key needed was an OrdServ one - where in the repo does it say it defaults to ordsurv?. 
c) that gb/os is not a good choice for the novice. Pain to have to go to the github and find a json example data file - maybe supply a few 'local' ones as part of the download so everything works out of the box? I have one gb layer and one json layer from a different country, so it's more side-by-side than overlaid :)
Maybe use one of the OL3 examples to get a boundary .json by clicking on a map?

I notice that the API fields retain their values but not the layer fields. Helpful if they all retained, maybe?

I had a few goes so have a few raster layers I don't need and no apparent way to remove them.  If it's a radio choice, guess there can never be more than one of them, can there?  I'd prefer if there was an opacity control so I could have more than one raster...

Please don't heed this - it's just a brain dump  - the fact that you've contributed all this good code is plenty and I for one am grateful.

**Comment by probins** [comment]
> There isn't much help on the page

yes. As I say, I plan to provide some user help at some point soon. As you've noticed, it's not very user-friendly atm.

> what are the other map provider codes

all those that are in lib/registry/sources/, and any other source can be added by adding an entry in this registry

> where in the repo does it say it defaults to ordsurv

it doesn't default to anything; if you add a gb/os layer you have to supply the api key for that layer, namely the OpenSpace one. See https://github.com/probins/map-make/blob/master/lib/registry/sources/gb/os.js

> I'd prefer if there was an opacity control so I could have more than one raster...

that won't work, as I'm not reprojecting raster layers, just redisplaying roughly the same area in the new projection. I found raster reprojection to be a bit slow and unreliable.

> Please don't heed this

it's useful to get feedback. Thank :-)

**Comment by probins** [comment]
> You pointed to:
> https://maps.peterrobins.co.uk/gb.html

I've fixed both this (which uses ol2 and will disappear later this month) and https://maps.peterrobins.co.uk/files/gb.html which is the ol3 demo I set up, and which was linked from the OS forum post on ol3. I will move the associated gb.js to the tld.

**Comment by zawsx** [comment]
https://maps.peterrobins.co.uk/gb.html
is still 'loading software
https://maps.peterrobins.co.uk/files/gb.html has no map render - just coords on a blank screen:
![image](https://cloud.githubusercontent.com/assets/6049993/15077958/d79794c6-13a8-11e6-82b3-298f1f2c66f9.png)

I want to populate my base layer map (of my postcode area here in London, UK) with data, and provide the commonly-available choice of changing the base layer to other providers. Thought to add an opacity slider for each layer which is where I encountered the reprojection issue.  I suppose that, if I simply switch layers out, I avoid reprojection but would still like to smoothly fade/wipe in.

What I am up to now is to just load 'featureless' tiles to the base and then be able to switch features on and off on top - streetnames for instance, but also postboxes and a whole range of stuff that doesn't come from OSM, like weather data and bus timings. Thought you could use a boundary auto-select to obtain the json but then again, what do I know?

**Comment by probins** [comment]
sorry, both those links should have read http://... it was the https that was causing them to hang (another issue for me to resolve). You can load all modules from the querystring, e.g. for OS and OSM zoomed to a particular coord map-make.html?r={"gb/os":"myapikey"},osm/osm&z=6&lat=52&lon=-1. There's another issue specifically when you use addlayer for OS, which I've not located yet. It's good that you test out all this stuff :-)

Are you meaning that you want a bbox-type vector load, i.e. that you get the data for the visible extent and then get a new extent when you pan the map? That is only partly implemented in map-make atm.

The more specific your requirements, the more likely it is you'll want to write your own code rather than use map-make.

**Comment by zawsx** [comment]
Thanks again  - it's helpful to me to read the code behind stuff - this looks intersting if you've not seen it: https://github.com/dpmcmlxxvi/olexp
